add modular folders
broadinstitute/ddp-angular pull request #1392
Opened 2022-06-15 20:47 UTC by josemanuel167

Add modular folders and make use of mat-drawer-container

2022-06-15 21:34 UTC, josemanuel167 commented
Activities component can't be moved because depends on DdpModule, if I try to load again DdpModule it throws this error:
![image](https://user-images.githubusercontent.com/98110251/173933779-51ede90b-f354-45c6-bfd6-d9f18e81d804.png)

2022-06-15 22:37 UTC, MocanaAtBroad commented
Without a ticket or description, I really cannot tell what you are trying to achieve.  Please explain what your goal is with this PR (creating a ticket or pointing to one would be good). And then in PR, try to add comments that walk the reviewer through your approach to solving the problem.

2022-06-15 23:03 UTC, josemanuel167 commented
Main goal for this is achieve a feature structure following best practices:
-- core
    -> module
-- feature
   feature-module
-- feature2..
   feature2-module
-- shared
   shared-module

In core module now you can find the main layout that is going to frame all feature pages.

Fon component now implements a responsive layout making use of <mat-drawer-container>, <mat-drawer-content>, and <mat-drawer>.

Folders structure now looks like this:

![image](https://user-images.githubusercontent.com/98110251/173955904-95245be8-3c71-4496-9c84-6a580c22ff34.png)

2022-06-16 05:54 UTC, GiCharkviani commented on ddp-workspace/projects/ddp-dsm-ui/src/app/FON/core/fon-routing.module.ts
> +      // {
I suggest not to leave a commented-out code.

2022-06-16 05:58 UTC, GiCharkviani requested changes
Jose, please before changing architecture (in this case folder structure and extra lazy-loaded module inside the same type of module), let's discuss because there are lots of things going on.
I also saw that you are having a problem with DdpModule and that was expected because you have duplicated its declaration since you've made the child lazy module and have imported DdpModule in both, parent and child modules (even though they are both lazy-loaded).

P.S. Let's for now just add new features, without changing any structure. Definitely, further improvements will take place later on, but for now, we've got priorities that we should be concentrated on.
P.P.S. Anyway, Thank you for your effort!

@alextanlan @MocanaAtBroad What are your thoughts?

2022-06-16 09:37 UTC, alextanlan commented
I agree that because of the fact that we are running out of time we should not change any not related to demo stuff, for instance the FON architecture. 
(see [current goals comment in Slack](https://broadinstitute.slack.com/archives/C02FZQST19S/p1655314783672549))
If we really need we can apply it later. And definitely any global changes/refactoring of the code should be discussed together.

2022-06-16 09:41 UTC, alextanlan commented
For now, I'd suggest to postpone this PR.

2022-07-20 22:57 UTC, closed without merging