[DSM] PEPPER-280
broadinstitute/ddp-angular pull request #1882
Opened 2022-11-17 21:00 UTC by pegahtah

applying the renames and also changing the names of the columns
<img width="594" alt="Screen Shot 2022-11-17 at 3 57 34 PM" src="https://user-images.githubusercontent.com/47120870/202558799-8004e203-ed17-4636-833a-1912b82fcb43.png">
<img width="1671" alt="Screen Shot 2022-11-17 at 3 57 57 PM" src="https://user-images.githubusercontent.com/47120870/202558802-edbee343-8026-4b19-ba33-22d7c2160983.png">
<img width="1676" alt="Screen Shot 2022-11-17 at 3 59 41 PM" src="https://user-images.githubusercontent.com/47120870/202558803-efdfc172-7a66-4f72-90a3-a3b2d5e8957f.png">
<img width="1679" alt="Screen Shot 2022-11-17 at 4 00 04 PM" src="https://user-images.githubusercontent.com/47120870/202558804-355d8ab2-a3e3-4561-bfc2-962dc5d7a31c.png">

2022-11-18 06:22 UTC, GiCharkviani submitted a review, later dismissed
LGTM

2022-11-21 15:09 UTC, SimoneMaiwald requested changes
I don't think all these parameters where changed

2022-11-28 16:29 UTC, SimoneMaiwald commented on ddp-workspace/projects/ddp-dsm-ui/src/app/filter-column/models/column.model.ts
> +  public static COLLABORATOR_SAMPLE_ID = new ParticipantColumn('Tumor Collaborator Sample ID', 'collaboratorSampleId', 't');
Can you also change that label on the tissue page then

2022-11-28 16:29 UTC, SimoneMaiwald commented on ddp-workspace/projects/ddp-dsm-ui/src/app/filter-column/models/column.model.ts
> +  public static COLLABORATOR_SAMPLE = new ParticipantColumn('Normal Collaborator Sample ID', 'bspCollaboratorSampleId', 'k');
same here on the sample tab

2022-11-28 16:30 UTC, pegahtah commented on ddp-workspace/projects/ddp-dsm-ui/src/app/filter-column/models/column.model.ts
> +  public static COLLABORATOR_SAMPLE_ID = new ParticipantColumn('Tumor Collaborator Sample ID', 'collaboratorSampleId', 't');
Oh yes good catch!

2022-11-28 17:01 UTC, pegahtah commented on ddp-workspace/projects/ddp-dsm-ui/src/app/tissue/tissue.component.html
> +      <td colspan="3">
I moved the colspan to here to fix a display bug for when tissue was not type block not to change how the tissue page looks like (introduced by another PR of mine, PEPPER-285 )

2022-11-28 17:03 UTC, SimoneMaiwald approved these changes

2022-11-28 17:03 UTC, ngigliotosBroad approved these changes

2022-11-28 17:09 UTC, merged