PEPPER-323 Fix playwright tests
broadinstitute/ddp-angular pull request #1917
Opened 2022-11-29 18:40 UTC by walejand

2022-11-29 22:12 UTC, aweng98 requested changes
I figured out a way to match `Out Team` text screenshot. See my comments. 
Also, when creating new or updating existing screenshots, also run `-u` in docker image (see README).

2022-11-29 22:12 UTC, aweng98 commented on playwright-e2e/tests/singular/contact-us/contact-us-page-visual.spec.ts
> +    await expect(headerText).toHaveScreenshot('our-team-text.png');
Insert `await expect(headerText).toHaveText('Our Team');` at line #12. Then don't have to update screenshot `our-team-text-chromium-darwin.png`. Restore that screenshot.

2022-11-30 14:42 UTC, aweng98 commented
LG. You only need to generate & update screenshots on Playwright docker image because Playwright tests run on docker image in CircleCI.

2022-11-30 16:27 UTC, juanseba21 approved these changes

2022-11-30 17:23 UTC, aweng98 approved these changes

2022-11-30 17:24 UTC, merged