Ddp 4564 manage cookie preferences
broadinstitute/ddp-angular pull request #215
Opened 2020-08-05 11:30 UTC by marat-mamytov

Current PR adds new feature for cookies preference management.

With the cookies banner user can now fully deal with cookies in 3 ways:
![image](https://user-images.githubusercontent.com/54633385/89403924-ecd9e780-d73a-11ea-96bc-6b8977bf7abc.png)

1) Before user makes a consent decision -> default cookie consent will be stored (object keys are simplified)
![image](https://user-images.githubusercontent.com/54633385/89404102-40e4cc00-d73b-11ea-9667-dbb0e38569cc.png)

2) Click on "Accept Cookies" button -> all cookies are accepted by default -> banner is dismissed
![image](https://user-images.githubusercontent.com/54633385/89404188-62de4e80-d73b-11ea-9939-8ee4b0a6f15c.png)

3) Click on "Reject Cookies" button -> all cookies but functional are rejected by default -> banner is dismissed
![image](https://user-images.githubusercontent.com/54633385/89404334-97eaa100-d73b-11ea-8e1c-76b667eb112b.png)

4) Click on "Manage Preferences" button -> opens panel -> user can opt-out/opt-in listed categories of cookies.
If no consent decision was previously made, by default pre-selected value is "Accept".
![image](https://user-images.githubusercontent.com/54633385/89405445-6377e480-d73d-11ea-8315-f4b275dd6019.png)

Click on "x" button -> state of consent was not changed -> panel  is dismissed, banner is displayed
Click on "Submit preferences" button -> updates the consent -> panel  and banner are dismissed
![image](https://user-images.githubusercontent.com/54633385/89404777-5c040b80-d73c-11ea-81d9-60b9f0cce2bb.png)

**"Privacy policy" button and "Manage Preferences" button are transformed into separate components**
=> This way these buttons can be added to any page to launch corresponding panels.

_Example:_ temporary locally added "Manage Preferences" button to the learn-more page for demonstration
_Privacy Policy page is in progress. But Cookies Preference Button component can be easily added_ as 
`<ddp-cookies-preferences-button></ddp-cookies-preferences-button>`
To style it in any way - pass need classes.

![image](https://user-images.githubusercontent.com/54633385/89406566-30365500-d73f-11ea-9922-85624f4013b2.png)

Click on the button -> launch manage preference panel
![image](https://user-images.githubusercontent.com/54633385/89406372-e2215180-d73e-11ea-9383-dc03b0de0142.png)

Default value is "Accept" if no decision was made. 
If consent was previously set, then panel picks up the current state of consent. 
"X" and "Submit preferences" buttons behaviour remains the same.

**For authenticated uses cookies preferences are saved into profile:**

New field `public cookiesPreferences: CookiesPreferences | null;` was added to the `UserProfile` model.
_Need backend support for storing this data._

_Example of PATCH request:_ 
![image](https://user-images.githubusercontent.com/54633385/89402349-82c04300-d738-11ea-97d2-287a1dcfda39.png)

If no CookiesPreference in the profile yet, data from Local Storage will be saved into profile. 
![image](https://user-images.githubusercontent.com/54633385/89402873-4f31e880-d739-11ea-92a9-ef32e200622a.png)

All changes in cookies preference will be stored in Local Storage and save into profile.
Next time log in cookies preferences form user's profile will prevail.

**Added logger to log update consent events**

2020-08-11 15:55 UTC, charlottedye commented
Question on this: 

"For authenticated uses cookies preferences are saved into profile:
New field public cookiesPreferences: CookiesPreferences | null; was added to the UserProfile model.
Need backend support for storing this data."

  I thought we decided not to do this.

2020-08-11 16:05 UTC, charlottedye requested changes
I ran the code locally to review the functionality before looking closely at the actual code and found a number of issues: go ahead and fix these and then re-test and check the acceptance criteria to make sure I didn't miss anything.  Also, I thought we decided not to put the cookie preferences in the profile, so we should make sure we're on the same page about the plan for that.

-_gat and _gat_platform sometimes get added before cookies are accepted or rejected
-When the user submits the cookie preferences banner without changing anything (I.e., when they select accept on analytics cookies), the _gid and _ga cookies are added immediately like they should be, but _gat_platform and _gat are added only after doing something like clicking on the header logo.
-Functional cookies and analytical categories are described differently.  Functional cookies are grouped by service and analytical cookies are not.  It would be better to either always group or never group.  At minimum, "Name" should probably mean the same thing for both categories.
-For functional cookies: It seems like we should include the actual name of the cookie here somewhere.  For example, PRION_cookies_consent, tcell_agent_policy_cache, tcell_agent_session_id, etc.  For example, maybe under name we could do something like: "TCell: tcell_agent_policy_cache, tcell_agent_session_id".
-For functional cookies: some groups have expiration listed as "various".  It seems like it would be better to specify the different expirations, either by specifying the expiration for each cookie in the category or just listing the possible expirations.  We could say things in local storage have an expiration of "none"; keep "session" for session storage; and list the actual time before expiration for actual cookies
-For functional cookies: Auth0, TCell, and Pepper platform should probably be capitalized 
-For functional cookies: the descriptions aren't really accurate for some of the categories.  User authorization makes sense for Auth0, although you could also describe it as user authentication or access control.  For Pepper platform, I don't recall what exactly the cookies are (pepper.PRION.irbsession will only be present in test environments so you don't need to include that.  You probably should include PRION_cookies_consent, and that would be for storing cookie preferences).  For TCell, description should say something about security, like website security or just security.
-For analytical cookies: It looks like there's also _gat_platform
-For analytical cookies: the description for _gat should probably indicate that this is for network calls to analytics services.  Maybe something like "throttling to increase the efficiency of analytics collection" (or something shorter if you can think of anything)
-On the welcome page, the join us button at the bottom looks different.  Seems like there was a change to the CSS for Button—primaryYellow.  If something using Button—primaryYellow needs to change, it should do that in a different CSS class

2020-08-11 16:05 UTC, charlottedye commented on ddp-workspace/projects/ddp-sdk/src/lib/models/userProfile.ts
> +    public cookiesPreferences: CookiesPreferences | null;
I thought we decided not to do the profile support.  If we are doing this, we probably need to fully implement it.

2020-08-11 16:19 UTC, marat-mamytov commented on ddp-workspace/projects/ddp-sdk/src/lib/models/userProfile.ts
> +    public cookiesPreferences: CookiesPreferences | null;
Removed saving to user's profile

2020-08-12 15:08 UTC, charlottedye commented
I thought I had mentioned this but don't see it in my comment, so just in case I left it out: there are at least two missing cookies not described here related to Google Analytics that appear after accepting or rejecting cookies and clicking on the Prion banner at the top.

2020-08-12 16:18 UTC, marat-mamytov commented
> I thought I had mentioned this but don't see it in my comment, so just in case I left it out: there are at least two missing cookies not described here related to Google Analytics that appear after accepting or rejecting cookies and clicking on the Prion banner at the top.

 @charlottedye 
I've added a few Pepper cookies stored in local storage: session_key, token, studyLanguage. They are set in SessionMementoService and LanguageService. 
+ Updated the cookies description and table in the cookie preferences modal.
+ Added manage preferences button to the policy page.
+ Fixed Button—primaryYellow styles
Please check if you'll have a chance.

But unfortunately,  I'm not getting _gat and _gat_platform added before cookies are accepted or rejected -> I'll investigate it more. I don't even have _gat cookie at all for some reason. 
And I'm not getting any additional GA cookies (at least two as you mentioned). Could you please write their names, I'll investigate it also.

2020-08-12 18:37 UTC, charlottedye commented
I recall at least one case where they showed up was after clicking accept
on the cookie banner and then clicking on the Prion logo in the header.
Try clearing cookies and storage and going to the page, clicking accept,
and then clicking on the Prion logo and see if those show up.  If not, I
can see if it's a configuration issue.  Then make sure things work and you
aren't seeing any cookies you aren't expecting when creating an account,
filling out a survey, logging out, and logging in, etc.  You could also try
searching source control for "_gat", "_gat_platform", and anything related
to analytics.  If you're still not seeing it after that, I can investigate
and that would probably mean either it's a configuration issue or it was
inadvertently fixed somehow.

On Wed, Aug 12, 2020 at 12:18 PM Marat <notifications@github.com> wrote:

> I thought I had mentioned this but don't see it in my comment, so just in
> case I left it out: there are at least two missing cookies not described
> here related to Google Analytics that appear after accepting or rejecting
> cookies and clicking on the Prion banner at the top.
>
> @charlottedye <https://github.com/charlottedye>
> I've added a few Pepper cookies stored in local storage: session_key,
> token, studyLanguage. They are set in SessionMementoService and
> LanguageService.
>
>    - Updated the cookies description and table in the cookie preferences
>    modal.
>    - Added manage preferences button to the policy page.
>    - Fixed Button—primaryYellow styles
>    Please check if you'll have a chance.
>
> But unfortunately, I'm not getting _gat and _gat_platform added before
> cookies are accepted or rejected -> I'll investigate it more. I don't even
> have _gat cookie at all for some reason.
> And I'm not getting any additional GA cookies (at least two as you
> mentioned). Could you please write their names, I'll investigate it also.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/broadinstitute/ddp-angular/pull/215#issuecomment-672973468>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AJPNM2J2VB2ZZ7J3DV2LQETSAK6FVANCNFSM4PVMACAA>
> .
>

2020-08-13 13:45 UTC, marat-mamytov commented
@charlottedye 
> Also, I thought we decided not to put the cookie preferences in the profile, so we should make sure we're on the same page about the plan for that.

Misunderstood, fixed, no saving into profile.

> -_gat and _gat_platform sometimes get added before cookies are accepted or rejected
> -When the user submits the cookie preferences banner without changing anything (I.e., when they select accept on analytics cookies), the _gid and _ga cookies are added immediately like they should be, but _gat_platform and _gat are added only after doing something like clicking on the header logo.

Fixed my local issue with _gat cookie. Thank you! =>  Now both _gat and _gat_platform are set **with** _ga and _gid on acceptance. And no _gat and _gat_platform cookies are added before consent.
![image](https://user-images.githubusercontent.com/54633385/90141116-825d2300-dd9c-11ea-9383-609a911b8218.png)

> -On the welcome page, the join us button at the bottom looks different. Seems like there was a change to the CSS for Button—primaryYellow. If something using Button—primaryYellow needs to change, it should do that in a different CSS class

Fixed.

Also fixed cookies list and descriptions.

2020-08-13 20:51 UTC, charlottedye requested changes
I tried to rebase this on the latest version of the Prion branch multiple times but it does not seem to be working.  It might be better if you do that or even start fresh with a new branch based on prion_frontend_migration_branch and put all your changes in one commit since this is all one ticket anyway.

Additionally, I ran the non-rebased version of this locally and there are some basic UI things in the cookie preferences window that appear to have been messed up at some point.  I'm assuming the extra space under the button and link at the bottom of the modal window for the your privacy tab was unintentional because it looks a little strange to me.  At at least one screen size (I noticed this at 1121px x 721px), the bottom section with the link and button starts at a different place on the modal on each tab.  Looks like I might have missed this on the initial review.  Of the three tab versions, I think the analytical cookies tab's version looks the best, personally, but pick something that looks reasonable and use it for all three.  

Nice work finding the additional cookies.

2020-08-14 05:29 UTC, closed without merging