[DSM]-PEPPER-948 download of onc history upload template
broadinstitute/ddp-angular pull request #2156
Opened 2023-07-12 10:17 UTC by GiCharkviani

[PEPPER-948](https://broadworkbench.atlassian.net/browse/PEPPER-948?focusedCommentId=80698&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-80698)

This is how it works:

https://github.com/broadinstitute/ddp-angular/assets/77500504/66ac203c-9b36-4591-87f5-334931287d69

2023-07-12 13:33 UTC, aweng98 commented
Works great. Can we have new button look like the other button with blue background to be consistent? Download Mail List button also has blue background.
<img width="178" alt="Screenshot 2023-07-12 at 9 30 58 AM" src="https://github.com/broadinstitute/ddp-angular/assets/35533885/a591aeac-87ba-43ff-b5e5-0c5e7720f6b1">

2023-07-12 14:15 UTC, denniscunningham requested changes
The Zip file name is stored in the 'Content-Disposition' 'attachment;filename=<filename>' header.

2023-07-12 20:30 UTC, GiCharkviani reviewed
File naming has been fixed

2023-07-13 12:08 UTC, denniscunningham approved these changes

2023-07-13 12:45 UTC, merged