DDP-4875: Data request button
broadinstitute/ddp-angular pull request #255
Opened 2020-08-27 13:49 UTC by marat-mamytov

Current PR is for frontend part of Data Request feature.

2020-08-27 21:03 UTC, charlottedye requested changes
See the comments--I think you could clean this up even a bit more by consolidating some things and making some things more general to fit additional use cases.  This is a big improvement, though!

2020-08-27 21:03 UTC, charlottedye commented on ddp-workspace/projects/toolkit/src/lib/components/activity/new-activity-in-modal-button.component.ts
> +      data: {activityGuid: this.activityGuid, createActivityInstance: true, modalName: this.modalName},
You could make this more flexible by calling this ActivityModalButtonComponent and having createActivityInstance be passed in the way activityGuid is.  I also don't think you need modalName here

2020-08-27 21:03 UTC, charlottedye commented on ddp-workspace/projects/toolkit/src/lib/components/activity/new-activity-in-modal-button.component.ts
> +      data: {activityGuid: this.activityGuid, createActivityInstance: true, modalName: this.modalName},
Instead of modalName, you can have a boolean for whether there should be a confirmation step at the end (maybe showFinalConfirmation) and then you could have confirmationMessageName (which would be Toolkit.DataRequest.Okay for our use case) and completeMessageName (which would be Toolkit.DataRequest.SubmitRequest for our use case).  See DataRequestComponent for more on how this would work...

2020-08-27 21:03 UTC, charlottedye commented on ddp-workspace/projects/toolkit/src/lib/components/activity/data-request-activity.component.ts
> +export class DataRequestComponent extends ActivityComponent implements OnInit, OnDestroy, AfterViewInit {
I find the way things are split between DataRequestComponent and NewActivityInModalComponent kind of confusing.  I think you should be able to make this one component: ModalActivityComponent.  You'd use the modified version of the data object I described in NewActivityInModalComponent.  If showFinalConfirmation is true, you'd use the logic you have here for which button label to display, although you'd use confirmationMessageName instead of Toolkit.DataRequest.Okay and completeMessageName instead of Toolkit.DataRequest.SubmitRequest.  If showFinalConfirmation is false, you would just show the submit request button (in fact, you could probably improve this further by letting users specify the text for next, previous, submit, and confirm buttons.  You could assume that the confirmation step is always the final step).

2020-08-27 21:03 UTC, charlottedye commented on ddp-workspace/projects/toolkit/src/lib/components/activity/data-request-activity.component.ts
> +  public submitDataRequest(): void {
You'd just call this something like nextPage(), because that's really what it does.

2020-08-27 21:03 UTC, charlottedye commented on ddp-workspace/projects/toolkit/src/lib/components/activity/data-request-activity.component.ts
> +    <div class="DataRequestModal--header" *ngIf="model && isLoaded">
See below--you could rename this ModalActivity--header or something

2020-08-27 21:03 UTC, charlottedye commented on ddp-workspace/projects/toolkit/src/lib/components/activity/data-request-activity.component.ts
> +  selector: 'toolkit-data-request-activity',
See below--you could change this to toolkit-modal-activity

2020-08-27 21:03 UTC, charlottedye commented on ddp-workspace/projects/toolkit/src/lib/components/activity/data-request-activity.component.ts
> +        <button (click)="isLastStep ? closeModal() : submitDataRequest()"
See below: you'd change submitDataRequest to nextPage()

2020-08-27 21:03 UTC, charlottedye commented on ddp-workspace/projects/toolkit/src/lib/components/activity/data-request-activity.component.ts
> +                class="Button DataRequestModal--submit col-lg-6 col-md-6 col-sm-6 col-xs-12"
See below: you'd change DataRequestModal--submit to ModalActivity--submit

2020-08-27 21:03 UTC, charlottedye commented on ddp-workspace/projects/toolkit/src/lib/components/activity/data-request-activity.component.ts
> +                ? ('Toolkit.DataRequest.Okay' | translate)
See below: instead, you'd do this: `? (data.confirmationMessageName | translate)`

2020-08-27 21:03 UTC, charlottedye commented on ddp-workspace/projects/toolkit/src/lib/components/activity/data-request-activity.component.ts
> +                : ('Toolkit.DataRequest.SubmitRequest' | translate)"></button>
See below: instead, you'd do this: `: (data.completeMessageName | translate)"></button>`

2020-08-27 21:03 UTC, charlottedye commented on ddp-workspace/projects/toolkit/src/lib/components/activity/new-activity-in-modal.component.ts
> +    public dialogRef: MatDialogRef<NewActivityInModalComponent>,
You could move anything relevant here into the ModalActivityComponent

2020-08-27 21:03 UTC, charlottedye commented on ddp-workspace/projects/toolkit/src/lib/components/privacy-policy/prionPrivacyPolicy.component.ts
> +    <section class="PageContent-section">
For the record, if I had more time, I'd go back and make this privacy policy into an activity, but I hadn't thought of that at the time and I don't think we have time now.

2020-09-01 14:08 UTC, marat-mamytov commented
> See the comments--I think you could clean this up even a bit more by consolidating some things and making some things more general to fit additional use cases. This is a big improvement, though!

Changed the following:
- selector name from 'toolkit-data-request-activity' to 'toolkit-modal-activity' and made modal activity is more general and configurable
- data object for modal: removed createActivityInstance and modalName props and added new props for showing the confirmation step and buttons
- modal activity methods
- classes from DataRequestModal to ModalActivity

Also tried the following improvement:
1) move code creating new activity instance into the button -> this way I can pass this new ready instanceGuid instead of activityGuid into modal
2) and combine two modal components into one
=> I liked this approach a lot! But I could not make it work for now. It either ended up with two activity instances and errors on multiple modal open, or activity was created at all.

Please advise did I got your idea correctly? If yes, I go for it one more time.

2020-09-02 17:38 UTC, charlottedye approved these changes

2020-09-02 17:38 UTC, merged