DDP-5433 enforce required mailing address fields via SDK configuration flag
broadinstitute/ddp-angular pull request #391
Opened 2020-12-11 22:54 UTC by MocanaAtBroad

2020-12-11 22:54 UTC, MocanaAtBroad commented on ddp-workspace/projects/ddp-sdk/src/lib/components/address/addressEmbedded.component.ts
> +        @Inject('ddp.config') private configuration: ConfigurationService,
Get the configuration

2020-12-11 22:55 UTC, MocanaAtBroad commented on ddp-workspace/projects/ddp-sdk/src/lib/components/address/addressEmbedded.component.ts
> +                (formValidStatusChanged)="formValidStatusChanged$.next($event)"
Getting the form status from the child component.

2020-12-11 22:56 UTC, MocanaAtBroad commented on ddp-workspace/projects/ddp-sdk/src/lib/components/address/addressEmbedded.component.ts
>          distinctUntilChanged(),
We care about the valid status for overall component valid status if configuration flag is set to true.

2020-12-11 22:58 UTC, MocanaAtBroad commented on ddp-workspace/projects/ddp-sdk/src/lib/components/address/addressInput.component.ts
> +
Not enough to emit on addressForm.valueChanges . Sometimes we set the form values from parent component with the emit event=false flag, so we need to merge that event here as well.

2020-12-14 10:11 UTC, fat23cat requested changes
Changes look good. But could you please fix the tests? Some of them seem to be broken.

2020-12-16 08:35 UTC, fat23cat requested changes
Just a couple of suggestions.

2020-12-16 08:35 UTC, fat23cat commented on ddp-workspace/projects/ddp-sdk/src/lib/components/address/addressEmbedded.component.spec.ts
> +import { ConfigurationService } from 'ddp-sdk';
```suggestion
import { ConfigurationService } from '../../services/configuration.service';
```

2020-12-16 08:35 UTC, fat23cat commented on ddp-workspace/projects/ddp-sdk/src/lib/components/address/addressEmbedded.component.spec.ts
> +fdescribe('AddressEmbeddedComponent', () => {
```suggestion
describe('AddressEmbeddedComponent', () => {
```

2020-12-16 14:48 UTC, fat23cat approved these changes

2020-12-16 14:50 UTC, merged